--- 
abstract: Use Danga::Socket From Callbacks
author: Copyright (c) Daisuke Maki <daisuke@endeworks.jp>
distribution_type: module
generated_by: Module::Install version 0.65
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Danga-Socket-Callback
no_index: 
  directory: 
    - inc
    - t
requires: 
  Danga::Socket: 0
version: 0.011
